Models/Medicine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Numerics;

namespace PharmaPulseApp.Models
{
    public class Medicine
    {
        [Key]
        public int Id { get; set; }


        [Display(Name = "Medicine Picture")]
        public string MedicinePictureUrl { get; set; }


        [Required(ErrorMessage = "Medicine's name is required")]
        [Display(Name = "Name")]
        [StringLength(100, ErrorMessage = "Medicine's name is too long")]
        public string Name { get; set; }


        [Display(Name = "Fabrication Date")]
        [DataType(DataType.Date)]
        public DateTime FabDate { get; set; }


        [Display(Name = "Expiration Date")]
        [DataType(DataType.Date)]
        public DateTime ExpDate { get; set; }


        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Price")]
        [DataType(DataType.Currency, ErrorMessage = "Price format is not valid ")]
        public double Price { get; set; }


        [Required(ErrorMessage = "Amount is required")]
        [Display(Name = "Amount")]
        public int Amount { get; set; }


        [Display(Name = "Description")]
        public string Description { get; set; }


        [Required(ErrorMessage = "Manufacturer's name is required")]
        [Display(Name = "Manufacturer Name")]
        [StringLength(100, ErrorMessage = "Manufacturer's name is too long")]
        public string ManufacturerName { get; set; }


        [Required]
        public int AgeRangeId { get; set; }
        [ForeignKey("AgeRangeId")]
        public AgeRange AgeRange { get; set; }


        [Required]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }


        public List<Pharmacy_Medicine> Pharmacy_Medicines { get; set; }
    }
}

Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using PharmaPulseApp.Data;
using PharmaPulseApp.Models;

namespace PharmaPulseApp.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ContactUsController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index()
        {
            var medicines = _appDbContext.Medicines.ToList();
            ViewBag.Medicines = medicines;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Request request)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Requests.Add(request);
                await _appDbContext.SaveChangesAsync();
                return RedirectToAction("Index"); 
            }

            var medicines = _appDbContext.Medicines.ToList();
            ViewBag.Medicines = medicines;
            return View(request);
        }
    }
}

Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PharmaPulseApp.Data;
using PharmaPulseApp.Models;

namespace PharmaPulseApp.Controllers
{
    public class MedicineController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public MedicineController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index()
        {
            var categoriesWithMedicines = _appDbContext.Categories
                .Include(c => c.Medicines)
                .ToList();

            return View(categoriesWithMedicines);
        }

       
        [HttpGet("Store/{page?}")]
        public IActionResult Store(int? page)
        {
            int pageSize = 9; 
            int pageNumber = page ?? 1; 

            int totalMedicines = _appDbContext.Medicines.Count();

            int medicinesToSkip = (pageNumber - 1) * pageSize;

            var paginatedMedicines = _appDbContext.Medicines
                                                .Skip(medicinesToSkip)
                                                .Take(pageSize)
                                                .ToList();  

            ViewBag.Medicines = paginatedMedicines;
            ViewBag.PageNumber = pageNumber; 
            ViewBag.TotalMedicines = totalMedicines;
            ViewBag.PageSize = pageSize;

            return View();
        }



        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("MedicineNotFound");
            }

            var medicine = await _appDbContext.Medicines
                .Include(m => m.AgeRange)
                .Include(m => m.Category)
                .Include(m => m.Pharmacy_Medicines)
                .ThenInclude(pm => pm.Pharmacy)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (medicine == null)
            {
                return View("MedicineNotFound");
            }

            return View(medicine);
        }


        public async Task<IActionResult> DetailsByName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return View("MedicineNotFound");
            }

            var medicine = await _appDbContext.Medicines
                .Include(m => m.AgeRange)
                .Include(m => m.Category)
                .Include(m => m.Pharmacy_Medicines) 
                    .ThenInclude(pm => pm.Pharmacy) 
                .FirstOrDefaultAsync(m => m.Name == name);

            if (medicine == null)
            {
                return View("MedicineNotFound");
            }

            return View("Details", medicine);
        }


        public async Task<IActionResult> MedicinesByPharmacy(int pharmacyId)
        {
            var pharmacy = await _appDbContext.Pharmacies
                .Include(p => p.Pharmacy_Medicines)
                .ThenInclude(pm => pm.Medicine)
                .FirstOrDefaultAsync(p => p.Id == pharmacyId);

            if (pharmacy == null)
            {
                return View("MedicineNotFound");
            }

            var medicines = pharmacy.Pharmacy_Medicines
                .Select(pm => pm.Medicine)
                .ToList();

            return View(medicines);
        }
    }
}

Controllers/PharmacyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PharmaPulseApp.Data;

namespace PharmaPulseApp.Controllers
{
    public class PharmacyController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public PharmacyController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public async Task<IActionResult> Index()
        {
            var pharmacies = await _appDbContext.Pharmacies.ToListAsync();
            return View(pharmacies);
        }

        public async Task<IActionResult> Details(int id)
        {
            var pharmacy = await _appDbContext.Pharmacies
                .FirstOrDefaultAsync(p => p.Id == id);

            if (pharmacy == null)
            {
                return View("PharmacyNotFound");
            }

            return View(pharmacy);
        }

        public async Task<IActionResult> DetailsByName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return View("PharmacyNotFound");
            }

            var pharmacy = await _appDbContext.Pharmacies
                .FirstOrDefaultAsync(p => p.Name == name);

            if (pharmacy == null)
            {
                return View("PharmacyNotFound");
            }

            return View("Details", pharmacy);
        }
    }
}

Views/Medicine/Details.cshtml
@model PharmaPulseApp.Models.Medicine

@{
    ViewData["Title"] = "Medicine Details";
}

<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Medion</title>

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700|Roboto:400,700&display=swap" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />


    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="~/css/2style.css">

    <link rel="stylesheet" href="~/css/1bootstrap.min.css">
    <link rel="stylesheet" href="~/css/1magnific-popup.css">
    <link rel="stylesheet" href="~/css/1jquery-ui.css">
    <link rel="stylesheet" href="~/css/1owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/1owl.theme.default.min.css">


    <link rel="stylesheet" href="~/css/1aos.css">

    <link rel="stylesheet" href="~/css/1style.css">

</head>

<body class="sub_page">
    <div class="hero_area">

        <header class="header_section">
            <div class="container">
                <div class="top_contact-container">
                    <div class="tel_container">
                        <a href="">
                            <img src="~/images/telephone-symbol-button.png" alt=""> Call : +994 55 850 57 81
                        </a>
                    </div>
                    <div class="social-container">
                        <a href="https://www.facebook.com/">
                            <img src="~/images/fb.png" alt="" class="s-1">
                        </a>
                        <a href="https://x.com/">
                            <img src="~/images/twitter.png" alt="" class="s-2">
                        </a>
                        <a href="https://www.instagram.com/">
                            <img src="~/images/instagram.png" alt="" class="s-3">
                        </a>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="">
                        <span>
                            İslamMed
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex  flex-column flex-lg-row align-items-center w-100 justify-content-between">
                            <ul class="navbar-nav  ">

                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Pharmacy" asp-action="Index"> Pharmacy </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Medicine" asp-action="Index"> Medicine </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Medicine" asp-action="Store"> Online Buy </a>
                                </li>


                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact us</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About"> About </a>
                                </li>

                            </ul>

                            <form class="form-inline" method="get" action="@Url.Action("DetailsByName", "Home")">
                                <input type="search" name="name" placeholder="Search" class="form-control mr-2">
                                <button class="btn my-2 my-sm-0 nav_search-btn" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </form>


                            <div class="login_btn-contanier ml-0 ml-lg-5">
                                <a asp-area="" asp-controller="User" asp-action="Login">
                                    <img src="~/images/user.png" alt="">
                                    <span>
                                        Login
                                    </span>
                                </a>
                            </div>

                            <div class="login_btn-contanier ml-0 ml-lg-5">
                                <a asp-area="" asp-controller="User" asp-action="Register">
                                    <img src="~/images/user.png" alt="">
                                    <span>
                                        Register
                                    </span>
                                </a>
                            </div>

                        </div>
                    </div>

                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>


    <div class="container">
        <div class="row">

            <div class="col-md-5 mr-auto">
                <div class="border text-center">
                    <img src="@Model.MedicinePictureUrl" alt="Image" class="img-fluid p-5" style="width: 800px; height: 600px;">
                </div>

            </div>

            <div class="col-md-6">

                <h2 class="text-black">@Model.Name</h2>
                <p><strong>Amount:</strong> @Model.Amount</p>
                <p><strong>Description:</strong> @Model.Description</p>

                <p>
                    <del>$@((Model.Price + 10).ToString("F2"))</del>
                    <strong class="text-primary h4">$@(Model.Price.ToString("F2"))</strong>
                </p>

                <div class="mb-5">
                    <div class="input-group mb-3" style="max-width: 220px;">
                        <div class="input-group-prepend">
                            <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                        </div>
                        <input type="text" class="form-control text-center quantity-input" value="1" placeholder=""
                               aria-label="Quantity" aria-describedby="button-addon1">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                        </div>
                    </div>
                </div>

                <p>
                    <a href="@Url.Action("Card", "User", new { medicineId = Model.Id })" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Card</a>
                </p>


                <div class="mt-5">
                    <ul class="nav nav-pills mb-3 custom-pill" id="pills-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#" role="tab"
                               aria-controls="pills-home" aria-selected="true">Medicine Information</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <table class="table custom-table mt-5">
                                <thead>
                                    <tr>
                                        <th>Fabrication Date</th>
                                        <th>Expiration Date</th>
                                        <th>Manufacturer Name</th>
                                        <th>Age Range</th>
                                        <th>Category</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>@Model.FabDate.ToString("d/MMMM/yyyy")</td>
                                        <td>@Model.ExpDate.ToString("d/MMMM/yyyy")</td>
                                        <td>@Model.ManufacturerName</td>
                                        <td>@Model.AgeRange.Name</td>
                                        <td>@Model.Category.Name</td>
                                    </tr>
                                </tbody>
                            </table>

                            @if (Model.Pharmacy_Medicines != null && Model.Pharmacy_Medicines.Any())
                            {
                                <h3>Pharmacies Selling This Medicine:</h3>
                                <ul>
                                    @foreach (var pharmacy in Model.Pharmacy_Medicines.Select(pm => pm.Pharmacy))
                                    {
                                        <li>@pharmacy.Name - @pharmacy.Address - @pharmacy.PhoneNumber</li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <p>No pharmacies are selling this medicine currently.</p>
                            }

                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <table class="table custom-table">
                                <tbody>
                                    <tr>
                                        <td>HPIS CODE</td>
                                        <td class="bg-light">999_200_40_0</td>
                                    </tr>
                                    <tr>
                                        <td>HEALTHCARE PROVIDERS ONLY</td>
                                        <td class="bg-light">No</td>
                                    </tr>
                                    <tr>
                                        <td>LATEX FREE</td>
                                        <td class="bg-light">Yes, No</td>
                                    </tr>
                                    <tr>
                                        <td>MEDICATION ROUTE</td>
                                        <td class="bg-light">Topical</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var minusButton = document.querySelector('.js-btn-minus');
            var plusButton = document.querySelector('.js-btn-plus');
            var quantityInput = document.querySelector('.quantity-input');

            minusButton.addEventListener('click', function () {
                var currentValue = parseInt(quantityInput.value);
                if (currentValue > 1) {
                    quantityInput.value = currentValue - 1;
                }
            });

            plusButton.addEventListener('click', function () {
                var currentValue = parseInt(quantityInput.value);
                quantityInput.value = currentValue + 1;
            });
        });
    </script>

   
</body>

Views/Medicine/Index.cshtml
@model IEnumerable<Category>

@{
    ViewData["Title"] = "List of Medicines";
}


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Medion</title>

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700|Roboto:400,700&display=swap" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">
    <div class="hero_area">

        <header class="header_section">
            <div class="container">
                <div class="top_contact-container">
                    <div class="tel_container">
                        <a href="">
                            <img src="images/telephone-symbol-button.png" alt=""> Call : +994 55 850 57 81
                        </a>
                    </div>
                    <div class="social-container">
                        <a href="https://www.facebook.com/">
                            <img src="~/images/fb.png" alt="" class="s-1">
                        </a>
                        <a href="https://x.com/">
                            <img src="~/images/twitter.png" alt="" class="s-2">
                        </a>
                        <a href="https://www.instagram.com/">
                            <img src="~/images/instagram.png" alt="" class="s-3">
                        </a>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="">
                        <span>
                            Islammed
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex  flex-column flex-lg-row align-items-center w-100 justify-content-between">
                           <ul class="navbar-nav  ">

                                <li class="nav-item active">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Pharmacy" asp-action="Index"> Pharmacy </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Medicine" asp-action="Index"> Medicine </a>
                                </li>

                                <li class="nav-item">
                                     <a class="nav-link" asp-area="" asp-controller="Medicine" asp-action="Store"> Online Buy </a>
                                </li>


                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact us</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About"> About </a>
                                </li>

                            </ul>

                            <form class="form-inline" method="get" action="@Url.Action("DetailsByName", "Medicine")">
                                <input type="search" name="name" placeholder="Search" class="form-control mr-2">
                                <button class="btn my-2 my-sm-0 nav_search-btn" type="submit">
                                <i class="fa fa-search"></i>
                                </button>
                            </form>


                            <div class="login_btn-contanier ml-0 ml-lg-5">
                                <a asp-area="" asp-controller="User" asp-action="Login">
                                    <img src="~/images/user.png" alt="">
                                    <span>
                                        Login
                                    </span>
                                </a>
                            </div>

                            <div class="login_btn-contanier ml-0 ml-lg-5">
                                <a asp-area="" asp-controller="User" asp-action="Register">
                                    <img src="~/images/user.png" alt="">
                                    <span>
                                        Register
                                    </span>
                                </a>
                            </div>

                        </div>
                    </div>

                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>



    <section class="health_section layout_padding">
        <div class="health_carousel-container">
            @foreach (var category in Model)
            {
                <h2 class="text-uppercase">@category.Name</h2>
                <div class="carousel-wrap layout_padding2">
                    <div class="owl-carousel">
                        @foreach (var medicine in category.Medicines)
                        {
                            <div class="item">
                                <div class="box">
                                    <div class="btn_container">
                                        <a href="@Url.Action("Details", "Medicine", new { id = medicine.Id })">Buy Now</a>
                                    </div>
                                    <div class="img-box">
                                        <img src="@medicine.MedicinePictureUrl" alt="@medicine.Name">
                                    </div>
                                    <div class="detail-box">
                                        <div class="star_container">
                                            @for (var i = 0; i < 5; i++)
                                            {
                                                <i class="fa fa-star @(i < medicine.Amount ? "fa-star" : "fa-star-o")" aria-hidden="true"></i>
                                            }
                                        </div>
                                        <div class="text">
                                            <h6>@medicine.Name</h6>
                                            <h6 class="price">
                                                <span>$</span>@medicine.Price
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            }
        </div>
    </section>




    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js">
    </script>
    <script type="text/javascript">
        $(".owl-carousel").owlCarousel({
            loop: true,
            margin: 10,
            nav: true,
            navText: [],
            autoplay: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
    </script>
    <script type="text/javascript">
        $(".owl-2").owlCarousel({
            loop: true,
            margin: 10,
            nav: true,
            navText: [],
            autoplay: true,

            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
    </script>
</body>

</html>

Views/Medicine/MedicineNotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-info">
                <div class="card-body">
                    <h1 class="card-title text-info">No medicine found with the provided criteria</h1>
                    <p class="card-text">We're sorry, but it seems that there are no medicines matching your search criteria.</p>
                    <hr />
                    <a class="btn btn-outline-info" asp-controller="Medicine" asp-action="Index">Back to Home Page</a>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #e3f2fd;
    }
</style>